before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y libzmq3-dev
  - sudo -E ./install-protobuf.sh
  - gem update bundler
language: ruby
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1
  - 2.2
  - jruby
  - rbx-2
env:
  - PROTOBUF_VERSION=2.6.1
  - PROTOBUF_VERSION=3.0.0-alpha-2
matrix:
  allow_failures:
    - rvm: rbx-2
    - env: PROTOBUF_VERSION=3.0.0-alpha-2
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/51a956bcd2b1854d6756
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
