language: ruby
rvm:
  - "1.9.3"
  - "2.0.0"
script: NO_COMPILE_TEST_PROTOS=1 bundle exec rake spec/lib
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/51a956bcd2b1854d6756
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
